### ISSUE TITLE
不支持图片本地上传

### ISSUE THREAD

**Issue by airzhanglin** [JakeLaoyu/v-umeditor#1]
不支持图片本地上传？

**Comment by JakeLaoyu** [comment]
![image](https://user-images.githubusercontent.com/16181940/45023674-9b65e100-b069-11e8-94bf-7284f02dcc55.png)

**Comment by JakeLaoyu** [comment]
本地上传要参考官方文档，和后端联调的。

**Comment by JakeLaoyu** [comment]
下载对服务端语言版本 [https://ueditor.baidu.com/website/umeditor.html](https://ueditor.baidu.com/website/umeditor.html)
