### ISSUE TITLE
无法找到该模块

### ISSUE THREAD

**Issue by duzhihao-github** [JakeLaoyu/v-umeditor#8]
下载完成后找不到包。
npm -6.9
v-umeditor: "^0.4.4",

**Comment by JakeLaoyu** [comment]
什么包，提供一下报错截图

**Comment by duzhihao-github** [comment]
> 什么包，提供一下报错截图

就是找不到这个包

`无法找到模块“v-umeditor”的声明文件。“/Users/duzhihao/Desktop/demo/vue-template/node_modules/v-umeditor/lib/vUeditor.min.js”隐式拥有 "any" 类型。`

就是这样的报错

**Comment by JakeLaoyu** [comment]
你用的TS？这个包没做ts

**Comment by duzhihao-github** [comment]
> 你用的TS？这个包没做TS
可能是我电脑都问题，我今天有下了一个包跟这个情况一样，都是在node_modules能找到引用是出错。我现在正在排查。用了重下，cnpm、yarn 、清缓存这些办法好像都没用。

**Comment by JakeLaoyu** [comment]
这个报错来自ts

**Comment by duzhihao-github** [comment]
> 这个报错来自ts
这个错误来自vscode。npm的报错是
`
This dependency was not found:

* v-umeditor in ./src/main.js

To install it, you can run: npm install --save v-umeditor
`
我先后试了npm和yarn都是找不到这个包。你可以尝试把包下载下来试一试看能不能正常导入

**Comment by JakeLaoyu** [comment]
使用 `0.4.7` 版本
